FROM ubuntu
MAINTAINER Malvika Sharan <smalvika.sharan@uni-wuerzburg.de>
ENV DEBIAN_FRONTEND noninteractive

FROM python:3.5

RUN apt-get update
RUN apt-get upgrade --yes
RUN apt-get install git bioperl python3-pip --yes --fix-missing

RUN mkdir -p source_files
RUN mkdir -p source_files/reference_db_files

#### Locally install nr database, please install it to run RaptorX, takes about 1.5 hours
RUN mkdir -p source_files/reference_db_files/nr
RUN wget -c -P source_files/reference_db_files/nr ftp://ftp.ncbi.nih.gov/blast/db/FASTA/nr.gz
RUN gunzip source_files/reference_db_files/nr/nr.gz
RUN source_files/reference_db_files/blast/makeblastdb -in source_files/reference_db_files/nr/nr -dbtype prot

### Get RaptorX
RUN mkdir -p source_files/reference_db_files/raptorx
RUN git clone https://github.com/Indicator/RaptorX-SS8.git source_files/reference_db_files/raptorx/raptorx-ss3-ss8

RUN perl source_files/reference_db_files/raptorx/raptorx-ss3-ss8/setup.pl \
-home source_files/reference_db_files/raptorx/raptorx-ss3-ss8 \
-blast source_files/reference_db_files/blast/psiblast \
-nr source_files/reference_db_files/nr/nr

# Psortb

RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
apt-get -y install supervisor && apt-get clean && \
rm -rf /var/lib/apt/lists/*
ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2
ENV APACHE_LOCK_DIR /var/lock/apache2
ENV APACHE_PID_FILE /var/run/apache2.pid

WORKDIR /usr/local/src
RUN echo '/usr/local/lib64' >>/etc/ld.so.conf
RUN wget http://www.psort.org/download/docker/pft2.3.4.docker64bit.tar.gz && \
tar zxvf pft2.3.4.docker64bit.tar.gz && cp pftools/pfscan /usr/local/bin/

RUN wget http://www.psort.org/download/libpsortb-1.0.tar.gz && \
tar zxvf libpsortb-1.0.tar.gz && cd libpsortb-1.0 && \
./configure && make && make install && ldconfig

RUN wget http://www.psort.org/download/bio-tools-psort-all.3.0.4.tar.gz && \
tar zxvf bio-tools-psort-all.3.0.4.tar.gz
WORKDIR /usr/local/src/bio-tools-psort-all

RUN wget http://www.psort.org/download/docker/psortb.defaults

RUN perl Makefile.PL && make && make install && cp -r psort /usr/local/psortb

RUN a2enmod cgid && \
wget http://www.psort.org/download/docker/apache.conf.fragment && \
cat apache.conf.fragment >> /etc/apache2/apache2.conf

WORKDIR /usr/local/src

RUN wget http://www.psort.org/download/docker/apache-svm.tar.gz && \
tar zxvf apache-svm.tar.gz && cd apache-svm && make && \
cp svmloc.conf /etc/apache2/conf-available/

RUN wget http://www.psort.org/download/docker/startup.txt && \
mv startup.txt startup.pl && \
wget http://www.psort.org/download/docker/apache-psort.conf && \
cp apache-psort.conf /etc/apache2/conf-available/

RUN wget http://www.psort.org/download/docker/apache-psortb.tar.gz && \
tar zxvf apache-psortb.tar.gz && cd apache-psortb \
&& perl Makefile.PL && make && make install

RUN cd /etc/apache2/conf-enabled/ && \
ln -s ../conf-available/svmloc.conf && \
ln -s ../conf-available/apache-psort.conf

RUN wget http://www.psort.org/download/docker/Request.pm && \
cp Request.pm /usr/share/perl5/Apache/Singleton/Request.pm

RUN wget http://www.psort.org/download/docker/CGI-FastTemplate-1.09.tar.gz
RUN tar zxvf CGI-FastTemplate-1.09.tar.gz
RUN CGI-FastTemplate-1.09 && perl Makefile.PL && make && make install

RUN cd /var/www/html && \
wget http://www.psort.org/download/docker/psort-web.tar.gz && \
tar zxvf psort-web.tar.gz

RUN rm -r pft2.3.4.docker64bit.tar.gz \
libpsortb-1.0.tar.gz \
libpsortb-1.0 \
bio-tools-psort-all.3.0.4.tar.gz \
bio-tools-psort-all

RUN /etc/init.d/apache2 restart
EXPOSE 80
CMD ["/opt/run.sh"]

# copy psort to global execute
RUN cp /usr/local/psortb/bin/psort /usr/local/bin

WORKDIR /tools

WORKDIR /home
